#!/usr/bin/env python3
"""Generate the fixed result/progress port for the ChainReactor adapters.

This public projection lacks engine-manifest-artifact-gen. The generator keeps
all SDK diagnostic operations in reproducible generated source until that
canonical tool is available here. Config projection remains explicit in the
small adapter and is checked by module and image conformance tests.
"""

import argparse
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
ENGINES = {
    "gogo_scan": ("gogo-scan-engine", "asset.host_port.v1", "HostPort", "EncodeHostPort"),
    "spray_scan": ("spray-scan-engine", "asset.directory.v1", "Directory", "EncodeDirectory"),
    "zombie_audit": ("zombie-audit-engine", "security.auth_finding.v1", "AuthFinding", "EncodeAuthFinding"),
}

TEMPLATE = '''// Code generated by tools/chainreactor-facade-gen. DO NOT EDIT.
// Source: strict engine.v5 engine.json and fixed result mapping.

package main

import (
    "context"
    "errors"
    "os"

    "github.com/yyhuni/lunafox/contracts/results"
    "github.com/yyhuni/lunafox/engine-go/protocol"
    "github.com/yyhuni/lunafox/engine-go/sdk"
)

const engineResultType = "{result_type}"

type engineInputs = interface {{
    SubdomainsPath(context.Context) (string, error)
    HostPortsPath(context.Context) (string, error)
    WebsiteURLsPath(context.Context) (string, error)
    EndpointURLsPath(context.Context) (string, error)
}}

type engineHandler func(context.Context, *protocol.EngineExecutionContext, *engineReportPort, engineInputs) error

type engineReportPort struct {{
    reporter sdk.Reporter
    diagnostics sdk.GeneratedDiagnostics
    sink sdk.ResultSink
    pending [][]byte
}}

func Run(handler engineHandler) {{
    if err := sdk.Run(func(ctx context.Context, snapshot *protocol.EngineExecutionContext, reporter sdk.Reporter, inputSet engineInputs) error {{
        if reporter == nil || handler == nil {{
            return errors.New("engine reporter and handler are required")
        }}
        diagnostics, err := reporter.GeneratedDiagnostics()
        if err != nil {{ return err }}
        if err := diagnostics.RegisterResultType(engineResultType); err != nil {{
            return diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
        }}
        sink, err := reporter.ResultSink(engineResultType)
        if err != nil {{
            return diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
        }}
        port := &engineReportPort{{reporter: reporter, diagnostics: diagnostics, sink: sink, pending: make([][]byte, 0, 128)}}
        if err := handler(ctx, snapshot, port, inputSet); err != nil {{
            return diagnostics.WrapFailure(sdk.GeneratedFailureHandler, err)
        }}
        return port.Flush(ctx)
    }}); err != nil {{
        _, _ = os.Stderr.WriteString("engine execution failed\\n")
        os.Exit(1)
    }}
}}

func (port *engineReportPort) Progress(ctx context.Context, message string) error {{
    if port == nil {{ return errors.New("engine progress port is required") }}
    return port.diagnostics.WrapFailure(sdk.GeneratedFailureProgressReport, port.reporter.ReportProgress(ctx, message))
}}

func (port *engineReportPort) Submit(ctx context.Context, item results.{item_type}) error {{
    if port == nil {{ return errors.New("engine result port is required") }}
    if err := port.diagnostics.ObserveResultReceived(engineResultType); err != nil {{
        return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
    }}
    encoded, err := results.{encoder}(item)
    if err != nil {{ return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err) }}
    if err := port.diagnostics.ObserveResultEncoded(engineResultType); err != nil {{
        return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultEncode, err)
    }}
    port.pending = append(port.pending, []byte(encoded))
    if len(port.pending) == cap(port.pending) {{ return port.Flush(ctx) }}
    return nil
}}

func (port *engineReportPort) Flush(ctx context.Context) error {{
    if port == nil {{ return errors.New("engine result port is required") }}
    if len(port.pending) == 0 {{ return nil }}
    items := make(chan []byte, len(port.pending))
    for _, payload := range port.pending {{ items <- payload }}
    close(items)
    if err := port.sink.Submit(ctx, items); err != nil {{
        return port.diagnostics.WrapFailure(sdk.GeneratedFailureResultSubmit, err)
    }}
    port.pending = port.pending[:0]
    return nil
}}
'''

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = []
    for directory, (command, result_type, item_type, encoder) in ENGINES.items():
        base = ROOT / "extensions" / "engines" / directory
        manifest = json.loads((base / "engine.json").read_text())
        if manifest["engineId"] != "engine.lunafox." + directory or manifest["execution"]["engineApiMajor"] != 2:
            raise SystemExit(f"unexpected Engine manifest: {directory}")
        path = base / "cmd" / command / "execution_run_generated.go"
        source = TEMPLATE.format(result_type=result_type, item_type=item_type, encoder=encoder)
        formatted = subprocess.run(["gofmt"], input=source, text=True, capture_output=True, check=True).stdout
        if args.check:
            if not path.exists() or path.read_text() != formatted:
                changed.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(formatted)
    if changed:
        raise SystemExit("generated Facades are stale: " + ", ".join(changed))

if __name__ == "__main__":
    main()
