CREATE TABLE IF NOT EXISTS auth_finding_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id INTEGER NOT NULL REFERENCES scan(id) ON DELETE CASCADE,
    url VARCHAR(2000) NOT NULL,
    service VARCHAR(8) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    account VARCHAR(128) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT auth_finding_snapshot_service_check CHECK (service IN ('http', 'https')),
    CONSTRAINT auth_finding_snapshot_kind_check CHECK (kind IN ('valid_credential', 'anonymous_access')),
    CONSTRAINT auth_finding_snapshot_account_check CHECK (
        (kind = 'valid_credential' AND account <> '') OR
        (kind = 'anonymous_access' AND account = '')
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_auth_finding_per_scan
    ON auth_finding_snapshot(scan_id, url, service, kind, account);
CREATE INDEX IF NOT EXISTS idx_auth_finding_scan_created_at_id
    ON auth_finding_snapshot(scan_id, created_at DESC, id DESC);
